### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by OdalisG** [OdalisG/EmployeeCrud#1]
:+1:  Create a README
:+1:  Push initial commit to GitHub
 

- [x] Create an Employee Credential Database

- [ ]  Create an authentication with one single login credential for Admins

- [ ]  See if you can Remove instead of Delete (Archive information)

- [x] Make sure to have comment lines

- [x] Update the default page to go straight to database instead of index
